.PHONY: compile generate

MSG ?= "Across the Great Wall, we can reach every corner in the world."

compile: compile-bash compile-csh compile-fish compile-ksh compile-ps1 compile-sh compile-tcsh compile-bat compile-zsh

compile-bash:
	bash Bourne-Again\ Shell.bash

compile-csh:
	csh C\ Shell.csh

compile-fish:
	fosh Friendly\ Interactive\ Shell.fish

compile-ksh:
	ksh Korn\ Shell.ksh

compile-ps1:
	powershell PowerShell.ps1

compile-sh:
	sh Shell.sh

compile-tcsh:
	tcsh Tenex\ C\ Shell.tcsh

compile-bat:
	cmd Windows\ Command\ Prompt.bat

compile-zsh:
	zsh Z\ Shell.zsh

# generate:
# 	bash resource/generator.sh $(MSG)
