.PHONY: compile generate

MSG ?= "Across the Great Wall, we can reach every corner in the world."

compile: compile-node compile-jsfuck

compile-node:
	node Node.js

compile-jsfuck:
	node JSFuck.js

# generate:
# 	bash resource/generator.sh $(MSG)
