.PHONY: compile generate vendor

MSG ?= "Across the Great Wall, we can reach every corner in the world."

compile:
	bash resource/compiler.sh Commata.,,,

# generate:
# 	bash resource/generator.sh $(MSG)

vendor:
	git clone https://github.com/totallyhuman/commata vendor
