.PHONY: compile generate

MSG ?= "Across the Great Wall, we can reach every corner in the world."

# compile:
# 	bash resource/compiler.sh Slashes.\/\/\/

# generate:
# 	bash resource/generator.sh $(MSG)
