.PHONY: compile generate

MSG ?= "Across the Great Wall, we can reach every corner in the world."

compile:
	scalac Scala.scala
	scala -classpath . Scala

# generate:
# 	bash resource/generator.sh $(MSG)
