.PHONY: compile generate

MSG ?= "Across the Great Wall, we can reach every corner in the world."

compile:
	java -jar vendor/ArnoldC.jar Arnoldc.arnoldc
	java Arnoldc

# generate:
# 	bash resource/generator.sh $(MSG)
