.PHONY: compile generate

MSG ?= "Across the Great Wall, we can reach every corner in the world."

compile:
	gfortran -std=f95 Fortran.f95 -o fortran
	fortran

# generate:
# 	bash resource/generator.sh $(MSG)
